"use client";
import { useState } from "react";
const modules=[{n:"01",title:"O ponto de partida",meta:"4 aulas · 32 min"},{n:"02",title:"Clareza e direção",meta:"6 aulas · 54 min"},{n:"03",title:"Hábitos que permanecem",meta:"5 aulas · 47 min"},{n:"04",title:"O plano em movimento",meta:"7 aulas · 1h 12 min"}];
export default function Plataforma(){const[screen,setScreen]=useState<"curso"|"area">("curso");const[checkout,setCheckout]=useState(false);const[access,setAccess]=useState(false);return <main className="learning-platform">
  <header className="nav shell platform-nav"><a className="brand" href="/"><span className="brand-mark">A</span><span>ACENDA <small>ESTUDOS</small></span></a><nav><button onClick={()=>setScreen("curso")} className={screen==="curso"?"active":""}>Conhecer o curso</button><a href="/">Site do autor</a></nav><button className="login" onClick={()=>setScreen("area")}>Minha área <span>↗</span></button></header>
  {screen==="curso"?<section className="course-page shell"><div className="course-intro"><p className="eyebrow orange">CURSO ONLINE · ACESSO POR 1 ANO</p><h1>Do insight<br/><em>à prática.</em></h1><p>Uma experiência de estudos completa, com aulas objetivas e exercícios para transformar conhecimento em ação.</p><ul><li>22 aulas objetivas</li><li>4 cadernos de exercícios</li><li>Certificado de conclusão</li><li>Acesso em qualquer dispositivo</li></ul></div><aside className="price-card"><span>EXPERIÊNCIA COMPLETA</span><h3>Curso Acenda</h3><p className="price"><small>12x de</small> R$ 29,70</p><p>ou R$ 297 à vista</p><button className="primary wide" onClick={()=>setCheckout(true)}>Quero começar agora <span>→</span></button><small>Demonstração · Nenhuma cobrança será feita</small></aside><div className="curriculum"><p className="eyebrow orange">CONTEÚDO DO CURSO</p><h2>Seu caminho, passo a passo.</h2>{modules.map((m,i)=><div className="module" key={m.n}><span>{m.n}</span><div><b>{m.title}</b><small>{m.meta}</small></div><span>{i===0?"▶":"⌁"}</span></div>)}</div></section>:<section className="student shell"><div className="student-head"><div><p className="eyebrow orange">MINHA ÁREA DE ESTUDOS</p><h1>{access?"Continue aprendendo.":"Conteúdo exclusivo."}</h1><p>{access?"Retome sua jornada de onde parou.":"Compre o curso para liberar aulas, exercícios e certificado."}</p></div><span className="avatar">AM</span></div>{access?<div className="learning"><div className="progress-card"><p>SEU PROGRESSO</p><b>8%</b><div><span/></div><small>2 de 22 aulas concluídas</small></div><h2>Seus módulos</h2>{modules.map((m,i)=><button className="lesson" key={m.n}><span className={i?"locked-dot":"play-dot"}>{i?"•":"▶"}</span><div><b>{m.title}</b><small>{m.meta}</small></div><span>→</span></button>)}</div>:<div className="locked"><div className="lock-icon">⌁</div><h2>Você ainda não possui acesso</h2><p>Conheça o curso e libere sua jornada de estudos.</p><button className="primary" onClick={()=>setScreen("curso")}>Conhecer o curso <span>→</span></button></div>}</section>}
  <footer><div className="shell"><div className="brand"><span className="brand-mark">A</span><span>ACENDA ESTUDOS</span></div><p>Aprenda no seu ritmo.</p><div><a href="/">Voltar ao site do autor</a></div></div></footer>
  {checkout&&<div className="modal-backdrop" onMouseDown={()=>setCheckout(false)}><div className="modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setCheckout(false)} aria-label="Fechar">×</button><p className="eyebrow orange">DEMONSTRAÇÃO GRATUITA</p><h2>Simular compra do curso</h2><p>Nesta demonstração não há cobrança. Continue para visualizar a área do aluno liberada.</p><div className="order"><span>Curso Acenda</span><b>R$ 297,00</b></div><button className="primary wide" onClick={()=>{setAccess(true);setCheckout(false);setScreen("area")}}>Liberar acesso demonstrativo <span>→</span></button></div></div>}
 </main>}
