import SiteCommerce from "./SiteCommerce";
import Store from "./Store";
const platformUrl="http://localhost:3001";
export default function Home(){return <main className="institutional">
<header className="nav shell"><a className="brand" href="#inicio"><span className="brand-mark">MV</span><span>MATHEUS VIDAL</span></a><nav><a href="#inicio">Início</a><a href="#sobre">Sobre</a><a href="#livros">Livros</a><a href="#loja">Loja</a><a href="#cursos">Cursos</a></nav><a className="login" href="#contato">Entrar em contato <span>↓</span></a></header>
<section id="inicio" className="person-hero shell"><div className="orbit"/><div className="orbit orbit-two"/><div className="person-copy"><p className="eyebrow"><span/> PREGADOR · AUTOR · PALESTRANTE</p><h1>Uma mensagem<br/>que <em>transforma.</em></h1><p>Fé, conhecimento e caminhos práticos para pessoas que desejam crescer com propósito e fazer a diferença.</p><div className="actions"><a className="primary" href="#sobre">Conheça minha história <span>↓</span></a><a className="text-link" href="#contato">Agendar uma conversa <span>↓</span></a></div></div><div className="person-photo"><div className="orange-halo"/><img src="/autor-principal.png" alt="Matheus Vidal, pregador, autor e palestrante"/><p>PROPÓSITO <span>→</span> MOVIMENTO</p></div></section>
<section id="sobre" className="about-person"><div className="shell about-grid"><div><p className="eyebrow orange">SOBRE MATHEUS</p><h2>Fé, conhecimento<br/>e <em>propósito.</em></h2></div><div className="about-text"><p>Matheus Vidal é pregador, autor e palestrante. Transforma experiências e conhecimento bíblico em mensagens capazes de aproximar pessoas de Deus e dos seus propósitos.</p><p>Seu trabalho une fé, liderança e desenvolvimento humano em uma linguagem clara, acolhedora e aplicável à vida real.</p><div className="author-stats"><div><b>12+</b><span>ANOS DE EXPERIÊNCIA</span></div><div><b>80+</b><span>PALESTRAS E EVENTOS</span></div><div><b>30k</b><span>PESSOAS ALCANÇADAS</span></div></div></div></div></section>
<section id="livros" className="work-section shell"><div className="work-heading"><p className="eyebrow"><span/> LIVROS</p><h2>Palavras que<br/><em>permanecem.</em></h2></div><article className="book-card"><div className="book-cover"><small>UM LIVRO DE</small><b>MATHEUS<br/>VIDAL</b><strong>FÉ</strong><span>que produz movimento</span></div><div><p className="eyebrow orange">LIVRO EM DESTAQUE</p><h3>Uma mensagem para viver</h3><p>Um convite para transformar reflexão em atitude, reconhecendo a força da fé em cada escolha.</p><a className="text-link" href="#comprar">Comprar o livro <span>→</span></a></div></article></section>
<SiteCommerce/>
<Store/>
<section id="cursos" className="courses-bridge"><div className="shell bridge-grid"><div><p className="eyebrow orange">CURSOS ONLINE</p><h2>Seu próximo passo<br/>começa <em>agora.</em></h2><p>Conheça os cursos e acesse o outro site: a plataforma exclusiva de estudos.</p><a className="primary" href={platformUrl}>Abrir a plataforma <span>↗</span></a></div><div className="platform-preview"><div className="preview-top"><span/><span/><span/></div><p>PLATAFORMA MATHEUS VIDAL</p><h3>Aprenda no seu ritmo.</h3><div className="preview-progress"><span/></div><small>Conteúdo · Exercícios · Certificado</small></div></div></section>
<footer><div className="shell"><div className="brand"><span className="brand-mark">MV</span><span>MATHEUS VIDAL</span></div><p>Uma mensagem que transforma.</p><div><a href="#sobre">Sobre</a><a href="#livros">Livros</a><a href={platformUrl}>Cursos</a></div></div></footer>
</main>}
