const whatsappMessage = encodeURIComponent("Olá! Conheci seu trabalho pelo site e gostaria de conversar sobre uma agenda.");
const whatsappUrl = `https://wa.me/?text=${whatsappMessage}`;

export default function Home() {
  return <main className="institutional">
    <header className="nav shell"><a className="brand" href="#inicio"><span className="brand-mark">A</span><span>ACENDA</span></a><nav><a href="#inicio">Início</a><a href="#sobre">Sobre</a><a href="#livros">Livros</a><a href="#cursos">Cursos</a></nav><a className="login" href={whatsappUrl} target="_blank" rel="noreferrer">Falar no WhatsApp <span>↗</span></a></header>
    <section id="inicio" className="person-hero shell"><div className="orbit" /><div className="orbit orbit-two" /><div className="person-copy"><p className="eyebrow"><span /> AUTOR · PROFESSOR · PALESTRANTE</p><h1>Conhecimento<br />que <em>transforma.</em></h1><p>Ideias, experiências e caminhos práticos para pessoas que desejam crescer com propósito e fazer a diferença.</p><div className="actions"><a className="primary" href="#sobre">Conheça minha história <span>↓</span></a><a className="text-link" href={whatsappUrl} target="_blank" rel="noreferrer">Agendar uma conversa <span>↗</span></a></div></div><div className="person-photo"><div className="orange-halo" /><img src="/autor-principal.png" alt="Retrato do autor, professor e palestrante" /><p>PROPÓSITO <span>→</span> MOVIMENTO</p></div></section>
    <section id="sobre" className="about-person"><div className="shell about-grid"><div><p className="eyebrow orange">SOBRE MIM</p><h2>Uma trajetória dedicada<br />a desenvolver <em>pessoas.</em></h2></div><div className="about-text"><p>Professor, autor e palestrante, transforma vivências profissionais e conhecimento em conversas capazes de aproximar pessoas dos seus objetivos.</p><p>Seu trabalho une educação, liderança e propósito em uma linguagem clara, humana e aplicável à vida real.</p><div className="author-stats"><div><b>12+</b><span>ANOS DE EXPERIÊNCIA</span></div><div><b>80+</b><span>PALESTRAS E EVENTOS</span></div><div><b>30k</b><span>PESSOAS ALCANÇADAS</span></div></div></div></div></section>
    <section id="livros" className="work-section shell"><div className="work-heading"><p className="eyebrow"><span /> LIVROS</p><h2>Palavras que<br /><em>permanecem.</em></h2></div><article className="book-card"><div className="book-cover"><small>UM LIVRO SOBRE</small><b>PROPÓSITO<br />E AÇÃO</b><strong>ACENDA</strong><span>o que move você</span></div><div><p className="eyebrow orange">LIVRO EM DESTAQUE</p><h3>Acenda</h3><p>Um convite para transformar reflexão em atitude, reconhecendo a força que existe em cada escolha.</p><a className="text-link" href="#contato">Quero conhecer o livro <span>→</span></a></div></article></section>
    <section id="cursos" className="courses-bridge"><div className="shell bridge-grid"><div><p className="eyebrow orange">CURSOS ONLINE</p><h2>Seu próximo passo<br />começa <em>agora.</em></h2><p>Conheça os cursos, veja o conteúdo completo e acesse a plataforma exclusiva de estudos.</p><a className="primary" href="/plataforma">Ir para a plataforma <span>→</span></a></div><div className="platform-preview"><div className="preview-top"><span /><span /><span /></div><p>PLATAFORMA ACENDA</p><h3>Aprenda no seu ritmo.</h3><div className="preview-progress"><span /></div><small>Conteúdo · Exercícios · Certificado</small></div></div></section>
    <section id="contato" className="whatsapp-section shell"><div><p className="eyebrow"><span /> AGENDA E CONVITES</p><h2>Quer levar essa conversa<br />para o seu <em>evento?</em></h2><p>Palestras, treinamentos, entrevistas e projetos especiais. Fale diretamente pelo WhatsApp para consultar disponibilidade.</p></div><a className="whatsapp-card" href={whatsappUrl} target="_blank" rel="noreferrer"><span className="wa-icon">◔</span><div><small>ATENDIMENTO DIRETO</small><b>Conversar no WhatsApp</b><p>Clique para iniciar uma conversa</p></div><span>↗</span></a></section>
    <a className="floating-whatsapp" href={whatsappUrl} target="_blank" rel="noreferrer" aria-label="Falar pelo WhatsApp"><span>◔</span><small>Fale comigo</small></a>
    <footer><div className="shell"><div className="brand"><span className="brand-mark">A</span><span>ACENDA</span></div><p>Conhecimento que transforma.</p><div><a href="#sobre">Sobre</a><a href="#livros">Livros</a><a href="/plataforma">Cursos</a></div></div></footer>
  </main>;
}
