import Image from "next/image";
import SiteFooter from "./SiteFooter";
import SiteHeader from "./SiteHeader";
import WhatsAppContact from "./WhatsAppContact";

const platformUrl = "https://cursos-matheus-vidal.vercel.app";

export default function Home() {
  const personSchema = { "@context": "https://schema.org", "@type": "Person", name: "Matheus Vidal", jobTitle: ["Pregador", "Autor", "Palestrante"], url: "https://plataforma-theta-seven.vercel.app", image: "https://plataforma-theta-seven.vercel.app/autor-principal.png" };
  return <main className="institutional">
    <SiteHeader />
    <section id="inicio" className="person-hero shell"><div className="orbit" /><div className="orbit orbit-two" /><div className="person-copy"><p className="eyebrow"><span /> PREGADOR · AUTOR · PALESTRANTE</p><h1><span>Matheus Vidal:</span><br />livros, cursos e mensagens <em>que transformam.</em></h1><p>Conheça o trabalho de Matheus Vidal e encontre mensagens, livros e cursos cristãos para crescer na fé, na liderança e no propósito.</p><div className="actions"><a className="primary" href="#sobre">Conheça minha história <span>↓</span></a><a className="text-link" href="#contato">Consultar agenda <span>→</span></a></div></div><div className="person-photo"><div className="orange-halo" /><Image src="/autor-principal.png" fill sizes="(max-width: 850px) 100vw, 46vw" alt="Matheus Vidal, pregador, autor e palestrante" priority /><p>PROPÓSITO <span>→</span> MOVIMENTO</p></div></section>
    <section id="sobre" className="about-person"><div className="shell about-grid"><div><p className="eyebrow orange">SOBRE MATHEUS</p><h2>Conheça Matheus Vidal, pregador, autor e palestrante.</h2></div><div className="about-text"><p>Matheus Vidal transforma experiências e conhecimento bíblico em mensagens capazes de aproximar pessoas de Deus e dos seus propósitos.</p><p>Seu trabalho une fé, liderança e desenvolvimento humano em uma linguagem clara, acolhedora e aplicável à vida real.</p><div className="author-stats"><div><b>12+</b><span>ANOS DE EXPERIÊNCIA</span></div><div><b>80+</b><span>PALESTRAS E EVENTOS</span></div><div><b>30k</b><span>PESSOAS ALCANÇADAS</span></div></div></div></div></section>
    <section className="work-section shell"><div className="work-heading"><p className="eyebrow"><span /> LIVRO DE MATHEUS VIDAL</p><h2>Palavras que permanecem e fortalecem a fé.</h2></div><article className="book-card"><div className="book-cover"><small>UM LIVRO DE</small><b>MATHEUS<br />VIDAL</b><strong>FÉ</strong><span>que produz movimento</span></div><div><p className="eyebrow orange">CONHEÇA A OBRA</p><h3>Uma mensagem para viver</h3><p>Descubra o livro, conheça sua proposta e simule a compra em uma página exclusiva.</p><a className="text-link" href="/livro">Conhecer e comprar o livro <span>→</span></a></div></article></section>
    <section className="store-teaser"><div className="shell store-teaser-grid"><div className="store-teaser-photo"><Image src="/store/jesus-casal.png" fill sizes="(max-width: 850px) 100vw, 52vw" alt="Camisetas cristãs da coleção MVLA" /></div><div><p className="eyebrow gold">LOJA MVLA · MODA CRISTÃ</p><h2>Roupas cristãs para vestir fé e propósito.</h2><p>Conheça camisetas com estampas exclusivas, inspiradas em mensagens bíblicas e criadas para expressar aquilo em que você crê.</p><a className="primary" href="/loja">Entrar na loja <span>→</span></a></div></div></section>
    <section id="cursos" className="courses-bridge"><div className="shell bridge-grid"><div><p className="eyebrow orange">CURSOS DE MATHEUS VIDAL</p><h2>Formação cristã para avançar com propósito.</h2><p>Acesse o site exclusivo da plataforma de estudos, escolha seu curso e acompanhe as aulas no seu ritmo.</p><a className="primary" href={platformUrl}>Abrir a plataforma de cursos <span>↗</span></a></div><div className="platform-preview"><div className="preview-top"><span /><span /><span /></div><p>PLATAFORMA MATHEUS VIDAL</p><h3>Aprenda no seu ritmo.</h3><div className="preview-progress"><span /></div><small>Conteúdo · Exercícios · Progresso</small></div></div></section>
    <WhatsAppContact />
    <SiteFooter />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(personSchema) }} />
  </main>;
}
